name: Node CI

on: [push]

jobs:
  certificate:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@master
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
    - name: test
      run: |
        npm i
        npm run test:rules
